[package]
name = "celestial_orbit_simulation"
version = "0.0.1"
authors = ["Adri <adrisoftdev@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = {version = "0.32.2", features = ["bundled", "static-link"] }
libm = "0.1.4"